---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
File rasterio/crs.pyx:592, in rasterio.crs.CRS.from_epsg()

File rasterio/_err.pyx:289, in rasterio._err.exc_wrap_int()

CPLE_AppDefinedError: PROJ: internal_proj_create_from_database: /Users/marzi/miniconda3/envs/snowenvMAC/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.

During handling of the above exception, another exception occurred:

CRSError                                  Traceback (most recent call last)
Cell In[1], line 23
     18 dates = get_input_dates("2024-06-01", "2023-11-01")
     20 # Function to actually get data, run processing, returns xarray dataset w/ daily time dimension
     21 #s1_sd = get_s1_snow_depth(area, dates, work_dir = './contrib/data/BPR_retrieval/')
     22 # s1_sd = retrieve_snow_depth(area, dates, work_dir = 'Users/Adrian/Desktop/BPR_retrieval/')
---> 23 s1_sd = retrieve_snow_depth(area, dates, work_dir = '/Users/marzi/Desktop/SpicySnow/')
     24 # s1_sd = retrieve_snow_depth(area, dates, work_dir = './BPR_retrieval/')
     25 
     26 # work_dir will be created if not present 
   (...)
     37 
     38 #s1_sd.to_netcdf(f'./BPR_snd2022.nc')
     39 s1_sd.to_netcdf(f'/Users/marzi/Desktop/BPR_snd2024.nc')
...
File rasterio/crs.pyx:852, in rasterio.crs.CRS.from_string()

File rasterio/crs.pyx:596, in rasterio.crs.CRS.from_epsg()

CRSError: The EPSG code is unknown. PROJ: internal_proj_create_from_database: /Users/marzi/miniconda3/envs/snowenvMAC/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.
